### PR TITLE
PWA fixes

### PR DESCRIPTION
**Pull request by icarito**
I noticed script-8 doesn't get accepted by Chromium as a PWA to be installed. Running the Lighthouse audit tool I noticed a couple of issues and found a service-worker that was not being registered.

I haven't fully been able to test it but looks like a good start! These patches increase our PWA score from 45 to 93 in my tests.

### CODE REVIEW

**Comment by gabrielflorit** [comment]
Interesting. How does this help you?

**Comment by icarito** [comment]
It allows to install on mobile as an App, without browser widgets.

My kids like to play with Script-8 and they have a tablet ;-)

Still, miss a way for them to save their work, and the touch controls
don't work very well, but one can make a 1000km trip by going step by
step...!

**Comment by gabrielflorit** [comment]
I LOVE your kids are using this ❤️  ❤️  ❤️ 

also very sorry that it only lets you save to gists. A "save to local" option would be ideal.

**Comment by gabrielflorit** [comment]
Re: this PR, we should look at this https://facebook.github.io/create-react-app/docs/making-a-progressive-web-app

**Comment by gabrielflorit** [comment]
Closing this for now until we can find a full solution.

**Pull request closed without merging**
