### PR TITLE
Simplify getting started

### PR DESCRIPTION
**Pull request by svenefftinge**
Cool project! 🎉 
This PR just adds a config and button to allow people playing around immediately. It uses Gitpod, a free online dev environment for Gitpod we have been working on for the path months. It allows for easier contributing to the project and generally playing around with script-8.

I configured it so that it automatically opens two terminals with
 - `yarn iframe-start``
 - `yarn start`

similar as you described for the local setup.

screenshot 2019-01-27 at 08 51 23

Try it out:

[Open in Gitpod](https://gitpod.io#snapshot/eb14e570-9663-4545-8fd1-ec06771ce99f)

### CODE REVIEW

**Comment by gabrielflorit** [comment]
Interesting, hadn't heard of this before. I tried clicking the link but nothing happened.

**Comment by svenefftinge** [comment]
You mean you clicked the button? Very strange it is a regular link. Just clicked it again.
You can open any github repo by just prefixing the github URL.

For instance this PR: [https://gitpod.io/#https://github.com/script-8/script-8.github.io/pull/149](https://gitpod.io/#https://github.com/script-8/script-8.github.io/pull/149)

**Comment by svenefftinge** [comment]
There was an issue with a CDN which only some users experienced. It has been fixed.

**Comment by gabrielflorit** [comment]
Well, this is an impressive project. Some neat magic going on here. I have some questions:

- how do I open a url with query params?
- will it track the latest changes? e.g. right now, script-8.github.io is at v0.1.168, but on gitpod I see it's at v0.1.165.

I have some further testing to do, but nice work.

**Comment by svenefftinge** [comment]
The button I shared here is a snapshot, i.e. a copy of a certain state.
The button in the readme will always use the master state.

Gitpod will always use the context that is provided, through the prefixed URL.
E.g.:

gitpod.io#https://github.com/script-8/script-8.github.io -> dev (default branch)
gitpod.io#https://github.com/script-8/script-8.github.io/tree/compressmap -> compressmap
gitpod.io#https://github.com/script-8/script-8.github.io/pull/149 -> my branch from my repo (i.e. this PR)

It also works on issues in which case gitpod creates a local branch `GH-<issue_nr>` that is branched from the default branch (`dev` in the case of this repo).

> how do I open a url with query params?

Could you elaborate what you mean?

**Comment by gabrielflorit** [comment]
> Could you elaborate what you mean?
A common workflow with this project is loading cassettes for debugging. This is done by specifying the cassette id, like this: https://script-8.github.io/?id=cd8d6811adb3afb472aaf7505729cf01

Is this possible?

**Comment by svenefftinge** [comment]
Sorry, I was travelling last week. Yes, it is. 
You can open any URL using the `Preview: Open URL` command (press F1 for the command palette).
Also Gitpod has a CLI, that allows to open the preview from the terminal, so in case the cassette id is known programmatically one could execute something like this:
```sh
gp preview $(gp url 3000)?id=$CASETTE_ID
```
Let me know if you want me to reopen the PR. I will be happy to help out in future if you have more questions.

**Pull request closed without merging**
