### PR TITLE
Add codetabs

### PR DESCRIPTION
**Pull request by gabrielflorit**

### CODE REVIEW

**Comment by gabrielflorit** [comment]
@icarito @colxi would you mind taking a look?

**Comment by colxi** [comment]
Sure! I'll take a look to it  by the end of the day. It has to be tested in the local environment right?

**Comment by gabrielflorit** [comment]
> Sure! I'll take a look to it by the end of the day. It has to be tested in the local environment right?

Yes and thank you.

**Comment by colxi** [comment]
Sorry i had a difficult day, and i could not check it. 
I realized there is what appears to be a a bug in the the Shelf , where POPULAR CASSETTES, are not sorted anymore by Plays (as it use to be)... unless of course, you are using another criteria to sort the cassettes, and this is intentional.

**Comment by gabrielflorit** [comment]
It is intentional indeed. I switched to frecency, a combination of frequency and recent visits. I'm using this https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm minus the `type of visit` part.

**Comment by colxi** [comment]
Cool stuff!

**Pull request merged**
