### PR TITLE
Fix map function to use Y coordinate

### PR DESCRIPTION
**Pull request by cakenggt**
Fixes issue https://github.com/script-8/script-8.github.io/issues/289

### CODE REVIEW

**Comment by cakenggt** [comment]
@gabrielflorit Is there any chance of getting this merged in?

**Comment by gabrielflorit** [comment]
Yes, and thank you for the pull request. I'll take care of it tomorrow.

**Comment by cakenggt** [comment]
Thanks!

**Comment by gabrielflorit** [comment]
This looks fine to me but I haven't tested it. @cakenggt would you be able to put together a cassette that shows the expected behavior? then I can deploy it.

**Comment by cakenggt** [comment]
This cassette should have a whole mountain in the lower right corner when this function works correctly, but it does not.

Correct behavior:
image

Buggy behavior:
image

**Comment by gabrielflorit** [comment]
aah you made this?! I have been thinking about it for days. I totally love the aesthetics. there's something quite haunting about it.

anyway! working on deploying now, hopefully it should be done soon

**Comment by cakenggt** [comment]
Thanks so much! I have you to thank for the amazing color palette you chose for this engine.

**Comment by gabrielflorit** [comment]
I noticed that `map(1, 1)` was doing what we expect `map(-1,-1)` to do. So I "fixed" it, but it might be confusing to some users. I've pushed the fix but haven't deployed yet. If you get a chance, test it on local.

**Comment by cakenggt** [comment]
I tested it out, but I can confirm that on at least my cassette the mountain drawing is incorrect again, so I'm not sure if other people's cassettes that used to rely on the backwards mx parameter will draw correctly anymore.

**Comment by gabrielflorit** [comment]
OK. I think it's best (for now) if I fix the y part but leave it "flipped". Less confusion for users.

**Pull request merged**
