### PR TITLE
Updated Codemirror to 5.43.0 and included search addon (fixes #124).

### LINKED ISSUE #124: In Lesson mode, enable moving to specific line

### PR DESCRIPTION
**Pull request by icarito**
:-)

### CODE REVIEW

**Comment by icarito** [comment]
Hotkeys are Ctrl-F for find and Ctrl-Shift-F for replace!

**Comment by gabrielflorit** [comment]
Oh exciting! will take a look

**Comment by gabrielflorit** [comment]
- this is a big commit. Is the codemirror upgrade necessary?
- did you write all the plugins yourself? If so, could you add comments? If not, could you point me to where you got them from?

And thank you!!!

**Comment by icarito** [comment]
a) It's not necessary to upgrade CodeMirror but it was easier than tracking down previous version (addons and core should match versions).
b) All plugins I got from the official current [CodeMirror distribution](https://codemirror.net/codemirror.zip) - unmodified, I only edited `index.html` to link them in. Didn't mean to take credit for those, they are verbatim.

**Comment by gabrielflorit** [comment]
Can you remove the codemirror upgrade from this PR? I'm going to update to 5.43 separately and use it for a bit. If nothing breaks, I'll merge this PR.

**Comment by gabrielflorit** [comment]
Looks good, thank you!

**Pull request merged**
