### PR TITLE
`polyStroke` and `polyFill`

### PR DESCRIPTION
**Pull request by Camto**
`polyStroke` takes `points` and `c` to draw the outline of a polygon on the screen with the `points` and `c` as colour.
`polyFill` takes `points` and `c` to draw a polygon on the screen with the `points` and `c` as colour.
`points` is an array of `[x, y]` form points. _(Could be in `{x: x, y: y}` form.)_

### CODE REVIEW

**Comment by gabrielflorit** [comment]
Thanks for this @Camto. I think calling `stroke` directly will make things look antialiased. I'm afraid we'll have to paint each pixel separately. What do you think?

**Comment by Camto** [comment]
I don't know really, but anti-aliasing happening seems likely. (Could be fixed using https://github.com/ssloy/tinyrenderer/wiki/Lesson-1:-Bresenham’s-Line-Drawing-Algorithm .)

This is unrelated, but should the `poly` functions take an angle and a center for rotation? I know how to do that.

**Comment by gabrielflorit** [comment]
@Camto Would you be up for rewriting this with Bresenham's? I'd like to avoid antialiasing.

Re: angle and center, yes, I think so. That seems pretty useful.

**Comment by Camto** [comment]
I'll do it when I can, the power will be out for 20-32.

**Comment by Camto** [comment]
@gabrielflorit I think it should be good now! Sorry I took about forever to make it. Also yes, they have been tested.

Added:
 * `line (x1, y1, x2, y2, c)`: draws a line from (`x1`, `y1`) to (`x2`, `y2`) of colour `c`.
 * `polyStroke (points, [angle, [center_x, center_y]], c)`: draws a polygon at `points` of colour `c`. Can be rotated by `angle` around (`center_x`, `center_y`), defaults to the middle of the polygon.

They both depend on the function `line ({ x1, y1, x2, y2, ctx, color })` in `line.js` in the same folder (similar to how `circle.js` is).

**Comment by Camto** [comment]
Simple example:

```
line(0, 10, 20, 30, 5);
polyStroke([[10, 0], [30, 30], [0, 30]], 90, 100, 100, 5);

**Comment by gabrielflorit** [comment]
Ooh very interesting, can't wait to try this out. I'm traveling for the next few days - I'll check this out ASAP. Thank you!

**Comment by Camto** [comment]
You're welcome!

**Pull request merged**
