### PR TITLE
Persist work

### PR DESCRIPTION
**Pull request by icarito**
Sorry for the repeat, this resolves issue with id from URL

### CODE REVIEW

**Comment by gabrielflorit** [comment]
Thank you for this. Some initial questions. What happens when:

- you go to the site, work on something, close tab, and come back?
- you go to the site, work on something, save, work on it a little bit more, not save, and come back?
- you load a cassette, close tab, and come back?
- you load a cassette, make changes to the code, and come back?

**Comment by icarito** [comment]
I'll try all of those with a fresh browser session:

* you go to the site, work on something, close tab, and come back?
  - You appear at HOME tab, but cassette has an asterisk and your work is there, unsaved, recovered from persisted state. Obs: Game appears paused, had to click "play".

* you go to the site, work on something, save, work on it a little bit more, not save, and come back?
Online version always trumps working buffer. If you come back with an GistID in the URL, the saved Gist will replace the working buffer.

* you load a cassette, close tab, and come back?
imagen
It loads cassette from network but maybe I'm running into a variant of #206 because I see the boot loop while it loads and strangely it didn't clear when running. This is all running on localhost:3000.

* you load a cassette, make changes to the code, and come back?
  Again, it will overwrite your local working copy with whatever is saved in the Gist.

Having tested these scenarios I see your point about this being tricky. May I suggest the criteria be **never loose a user's work**? If there's no Github account, a user needs to preserve their work. Thanks!

**Comment by icarito** [comment]
If you want to close the PR I guess you understand my point. If I come up with a better solution I'll share it!

**Comment by gabrielflorit** [comment]
Thank you for the detailed info. Indeed this is quite tricky! And I also agree that the user should not lose their work.

I'll leave this PR open because I think there are some good ideas here. I'll come back to it eventually.

**Comment by gabrielflorit** [comment]
closing due to the magnitude of this. it's probably easier to tackle as a number of smaller discrete PRs

**Pull request closed without merging**
